### ISSUE TITLE
Implement redirect on component

### ISSUE THREAD

**Issue by flick36** [ui-router/sample-app#26]
Hi i'm triying to implemente the [redirectTo](https://github.com/ui-router/sample-app/blob/0af1378c7c397f1efc5f6fb12282f3b3a005141e/transpiled/app/login.state.js) mehtod to a state that has a component, but i can't get it working i don't know where does the `$transition$.previous();` should come.

this is my state:
```
.state('app.login', {
    url: '/login',
    views: {
        'main@': {
            templateUrl: getView('login'),
            resolve: { returnTo: returnTo }
        }
    },
})
```

it never calls the function to resolve.

**Comment by christopherthielen** [comment]
Try putting the resolve on the state, not the view.  

Views shouldn't have a resolve property.

**Comment by flick36** [comment]
Thanks for the reply, Ok yes now it entersthe funtion  but how can i bind the resolve to the controller of the component? cause that view, doesnt have a controller it just a couple a dis for styling purpouse and then i call the component. using es6 like this:

```
class LoginFormController {
    constructor($auth) {
        'ngInject';

        this.$auth = $auth
    }
   $onInit(){
   }
}

export const LoginFormComponent = {
    templateUrl: './views/app/components/login-form/login-form.component.html',
    controller: LoginFormController,
    controllerAs: 'vm',
    bindings: {}
}
```
should is use the component as the view instead? :/ cause im triying to avoid that. but if it's the only way .-.
